[package]
name = "gblab-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
description = "High-performance GB28181 multi-device simulation core"
publish = false

[lints]
workspace = true

[dependencies]
encoding_rs.workspace = true
serde.workspace = true
serde_json.workspace = true
siprs = "0.1.2"
thiserror.workspace = true
tokio.workspace = true
tokio-util.workspace = true
rsmpeg.workspace = true

[dev-dependencies]
tempfile = "3"
