name: Build macOS

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-build
      - name: Build macOS application
        run: pnpm exec tauri build --bundles app
      - uses: actions/upload-artifact@v4
        with:
          name: gblab-macos
          path: target/release/bundle/macos/*.app
          if-no-files-found: error
